- name: Setup Docker + Telegraf Monitoring Stack
  hosts: monitoring
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Copy Telegraf config
      copy:
        src: ../telegraf/
        dest: /home/ubuntu/telegraf/

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu

